# Based on .travis.yml in `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: generic
sudo: required
dist: trusty

os:
  - linux
  - osx

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
    - LAPE_PWD=./tests/RunTests
    - LAPE_PKG=../../package
    - LAPE_FFI=../../extensions/ffi/test
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager
    - LAZ_VER=1.4.4
    - LAZ_VER=1.8.2

matrix:
  allow_failures:
    - env: LAZ_PKG=true
  include:
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.8.2  LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.8.2  LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=win64 --cpu=x86_64"
    - os: linux
      env: LAZ_VER=1.4.4  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm --widgetset=nogui"
    - os: linux
      env: LAZ_VER=1.8.2  LAZ_ENV=qemu-arm LAZ_OPT="--os=linux --cpu=arm --widgetset=nogui"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &
  - cd "$LAPE_PWD"

install:
  # Install prerequisites (fpc/lazarus/wine/qemu)
  - ./travis-lazarus/.travis.install.py

script:
  - lazbuild $LAZ_OPT "$LAPE_PKG/lape.lpk"
  - lazbuild $LAZ_OPT "LapeTest.lpi"
  - $LAZ_ENV ./LapeTest
  - cd "$LAPE_FFI" && ./runall.sh || true

notifications:
  email:
    on_success: false
    on_failure: change

